#!/usr/bin/env bash
set -x
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/a2_dynamic_blended_ch3.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/a2_dynamic_gated_ch8.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/a2_example.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossLSTM-1x16.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossLSTM-2x8.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossWN-feather.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossWN-lite.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossWN-nano.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/BossWN-standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/convnet_nobn.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/convnet_relu.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/convnet_silu.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/convnet_test.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_fft_rf2048.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_fft_rf320.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_fft_rf4096.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_fft_rf8192.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_nobias.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/linear_test.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/lstm_1x10.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/lstm_2x24.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/lstm_3x8.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/lstm_dyn_test.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/lstm.nam"
#Known Bug: RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/mock_a2.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/slimmable_container.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/slimmable_wavenet.nam"
#Known Bug: RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a1_secondary_act.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a1_standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_container.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_film_chaos_stress.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_film_full.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_film_input_mixin_pre.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_film_lite.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_full.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_lite.nam"
#Known Bug: RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_a2_max.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_condition_dsp.nam"
#Known Bug: RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_condition_lstm.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_dyn_free.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../NeuralAmpModeler-rs/tests/fixtures/models/wavenet_official.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/APP-EVH-Stealth100-Dialled-xSTD.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/BOG UU II Gain BAL CAB.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/Boss BD-2 H2O Mod T-12_00 G-12_00.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/ChandlerRedd47-Gain34-Standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/EVH-5150-Lite.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/little-bear-t7_phono-aux-tube-preamp_line-in_Standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/NEVE1073-Standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/SLAMMIN_MARSHALL_J45_VN9_TREBLEBOOSTER_P4_C.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/nam_t3k/UA610B-Gain+10-Standard.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/A2.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/lstm.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/my_model.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/slimmable_container.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/slimmable_wavenet.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/wavenet_a1_standard.nam"
#Known Bug: RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/wavenet_a2_max.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/wavenet_condition_dsp.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerCore/example_models/wavenet.nam"
RUST_BACKTRACE=full timeout --signal=SIGINT 3s nam-audio-pipe -m "../third-party/NeuralAmpModelerPlugin/REAPER/model.nam"
